// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: Consulta.proto

package Consulta

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Consulta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreDominio string `protobuf:"bytes,1,opt,name=NombreDominio,proto3" json:"NombreDominio,omitempty"`
}

func (x *Consulta) Reset() {
	*x = Consulta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Consulta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consulta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consulta) ProtoMessage() {}

func (x *Consulta) ProtoReflect() protoreflect.Message {
	mi := &file_Consulta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consulta.ProtoReflect.Descriptor instead.
func (*Consulta) Descriptor() ([]byte, []int) {
	return file_Consulta_proto_rawDescGZIP(), []int{0}
}

func (x *Consulta) GetNombreDominio() string {
	if x != nil {
		return x.NombreDominio
	}
	return ""
}

type Respuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP    string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Reloj string `protobuf:"bytes,2,opt,name=Reloj,proto3" json:"Reloj,omitempty"`
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Consulta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_Consulta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_Consulta_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *Respuesta) GetReloj() string {
	if x != nil {
		return x.Reloj
	}
	return ""
}

var File_Consulta_proto protoreflect.FileDescriptor

var file_Consulta_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x08, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x44, 0x6f, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x44, 0x6f, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x22, 0x31, 0x0a, 0x09,
	0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x6c,
	0x6f, 0x6a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x65, 0x6c, 0x6f, 0x6a, 0x32,
	0x56, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0f, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6c, 0x74, 0x61, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61,
	0x1a, 0x13, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x22, 0x00, 0x32, 0x54, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6c, 0x74, 0x61, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3b, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x12, 0x12, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x2e, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x1a, 0x13, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74,
	0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Consulta_proto_rawDescOnce sync.Once
	file_Consulta_proto_rawDescData = file_Consulta_proto_rawDesc
)

func file_Consulta_proto_rawDescGZIP() []byte {
	file_Consulta_proto_rawDescOnce.Do(func() {
		file_Consulta_proto_rawDescData = protoimpl.X.CompressGZIP(file_Consulta_proto_rawDescData)
	})
	return file_Consulta_proto_rawDescData
}

var file_Consulta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Consulta_proto_goTypes = []interface{}{
	(*Consulta)(nil),  // 0: Consulta.Consulta
	(*Respuesta)(nil), // 1: Consulta.Respuesta
}
var file_Consulta_proto_depIdxs = []int32{
	0, // 0: Consulta.ConsultaClienteService.ConsultaCliente:input_type -> Consulta.Consulta
	0, // 1: Consulta.ConsultaBrokerService.ConsultaBroker:input_type -> Consulta.Consulta
	1, // 2: Consulta.ConsultaClienteService.ConsultaCliente:output_type -> Consulta.Respuesta
	1, // 3: Consulta.ConsultaBrokerService.ConsultaBroker:output_type -> Consulta.Respuesta
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Consulta_proto_init() }
func file_Consulta_proto_init() {
	if File_Consulta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Consulta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consulta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Consulta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Consulta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_Consulta_proto_goTypes,
		DependencyIndexes: file_Consulta_proto_depIdxs,
		MessageInfos:      file_Consulta_proto_msgTypes,
	}.Build()
	File_Consulta_proto = out.File
	file_Consulta_proto_rawDesc = nil
	file_Consulta_proto_goTypes = nil
	file_Consulta_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConsultaClienteServiceClient is the client API for ConsultaClienteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsultaClienteServiceClient interface {
	ConsultaCliente(ctx context.Context, in *Consulta, opts ...grpc.CallOption) (*Respuesta, error)
}

type consultaClienteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsultaClienteServiceClient(cc grpc.ClientConnInterface) ConsultaClienteServiceClient {
	return &consultaClienteServiceClient{cc}
}

func (c *consultaClienteServiceClient) ConsultaCliente(ctx context.Context, in *Consulta, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/Consulta.ConsultaClienteService/ConsultaCliente", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsultaClienteServiceServer is the server API for ConsultaClienteService service.
type ConsultaClienteServiceServer interface {
	ConsultaCliente(context.Context, *Consulta) (*Respuesta, error)
}

// UnimplementedConsultaClienteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConsultaClienteServiceServer struct {
}

func (*UnimplementedConsultaClienteServiceServer) ConsultaCliente(context.Context, *Consulta) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsultaCliente not implemented")
}

func RegisterConsultaClienteServiceServer(s *grpc.Server, srv ConsultaClienteServiceServer) {
	s.RegisterService(&_ConsultaClienteService_serviceDesc, srv)
}

func _ConsultaClienteService_ConsultaCliente_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consulta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultaClienteServiceServer).ConsultaCliente(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Consulta.ConsultaClienteService/ConsultaCliente",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultaClienteServiceServer).ConsultaCliente(ctx, req.(*Consulta))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsultaClienteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Consulta.ConsultaClienteService",
	HandlerType: (*ConsultaClienteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultaCliente",
			Handler:    _ConsultaClienteService_ConsultaCliente_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Consulta.proto",
}

// ConsultaBrokerServiceClient is the client API for ConsultaBrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsultaBrokerServiceClient interface {
	ConsultaBroker(ctx context.Context, in *Consulta, opts ...grpc.CallOption) (*Respuesta, error)
}

type consultaBrokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsultaBrokerServiceClient(cc grpc.ClientConnInterface) ConsultaBrokerServiceClient {
	return &consultaBrokerServiceClient{cc}
}

func (c *consultaBrokerServiceClient) ConsultaBroker(ctx context.Context, in *Consulta, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/Consulta.ConsultaBrokerService/ConsultaBroker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsultaBrokerServiceServer is the server API for ConsultaBrokerService service.
type ConsultaBrokerServiceServer interface {
	ConsultaBroker(context.Context, *Consulta) (*Respuesta, error)
}

// UnimplementedConsultaBrokerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConsultaBrokerServiceServer struct {
}

func (*UnimplementedConsultaBrokerServiceServer) ConsultaBroker(context.Context, *Consulta) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsultaBroker not implemented")
}

func RegisterConsultaBrokerServiceServer(s *grpc.Server, srv ConsultaBrokerServiceServer) {
	s.RegisterService(&_ConsultaBrokerService_serviceDesc, srv)
}

func _ConsultaBrokerService_ConsultaBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consulta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultaBrokerServiceServer).ConsultaBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Consulta.ConsultaBrokerService/ConsultaBroker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultaBrokerServiceServer).ConsultaBroker(ctx, req.(*Consulta))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsultaBrokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Consulta.ConsultaBrokerService",
	HandlerType: (*ConsultaBrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultaBroker",
			Handler:    _ConsultaBrokerService_ConsultaBroker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Consulta.proto",
}
