// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Consulta.proto

package Consulta

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Datos struct {
	Url                  string   `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	Reloj                string   `protobuf:"bytes,2,opt,name=Reloj,proto3" json:"Reloj,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Datos) Reset()         { *m = Datos{} }
func (m *Datos) String() string { return proto.CompactTextString(m) }
func (*Datos) ProtoMessage()    {}
func (*Datos) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68347db208ce97b, []int{0}
}

func (m *Datos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datos.Unmarshal(m, b)
}
func (m *Datos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datos.Marshal(b, m, deterministic)
}
func (m *Datos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datos.Merge(m, src)
}
func (m *Datos) XXX_Size() int {
	return xxx_messageInfo_Datos.Size(m)
}
func (m *Datos) XXX_DiscardUnknown() {
	xxx_messageInfo_Datos.DiscardUnknown(m)
}

var xxx_messageInfo_Datos proto.InternalMessageInfo

func (m *Datos) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Datos) GetReloj() string {
	if m != nil {
		return m.Reloj
	}
	return ""
}

type RespuestaBroker struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Reloj                string   `protobuf:"bytes,2,opt,name=Reloj,proto3" json:"Reloj,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespuestaBroker) Reset()         { *m = RespuestaBroker{} }
func (m *RespuestaBroker) String() string { return proto.CompactTextString(m) }
func (*RespuestaBroker) ProtoMessage()    {}
func (*RespuestaBroker) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68347db208ce97b, []int{1}
}

func (m *RespuestaBroker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespuestaBroker.Unmarshal(m, b)
}
func (m *RespuestaBroker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespuestaBroker.Marshal(b, m, deterministic)
}
func (m *RespuestaBroker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespuestaBroker.Merge(m, src)
}
func (m *RespuestaBroker) XXX_Size() int {
	return xxx_messageInfo_RespuestaBroker.Size(m)
}
func (m *RespuestaBroker) XXX_DiscardUnknown() {
	xxx_messageInfo_RespuestaBroker.DiscardUnknown(m)
}

var xxx_messageInfo_RespuestaBroker proto.InternalMessageInfo

func (m *RespuestaBroker) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *RespuestaBroker) GetReloj() string {
	if m != nil {
		return m.Reloj
	}
	return ""
}

type Consulta struct {
	NombreDominio        string   `protobuf:"bytes,1,opt,name=NombreDominio,proto3" json:"NombreDominio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consulta) Reset()         { *m = Consulta{} }
func (m *Consulta) String() string { return proto.CompactTextString(m) }
func (*Consulta) ProtoMessage()    {}
func (*Consulta) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68347db208ce97b, []int{2}
}

func (m *Consulta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consulta.Unmarshal(m, b)
}
func (m *Consulta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consulta.Marshal(b, m, deterministic)
}
func (m *Consulta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consulta.Merge(m, src)
}
func (m *Consulta) XXX_Size() int {
	return xxx_messageInfo_Consulta.Size(m)
}
func (m *Consulta) XXX_DiscardUnknown() {
	xxx_messageInfo_Consulta.DiscardUnknown(m)
}

var xxx_messageInfo_Consulta proto.InternalMessageInfo

func (m *Consulta) GetNombreDominio() string {
	if m != nil {
		return m.NombreDominio
	}
	return ""
}

type Respuesta struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Reloj                string   `protobuf:"bytes,2,opt,name=Reloj,proto3" json:"Reloj,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Respuesta) Reset()         { *m = Respuesta{} }
func (m *Respuesta) String() string { return proto.CompactTextString(m) }
func (*Respuesta) ProtoMessage()    {}
func (*Respuesta) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68347db208ce97b, []int{3}
}

func (m *Respuesta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Respuesta.Unmarshal(m, b)
}
func (m *Respuesta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Respuesta.Marshal(b, m, deterministic)
}
func (m *Respuesta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Respuesta.Merge(m, src)
}
func (m *Respuesta) XXX_Size() int {
	return xxx_messageInfo_Respuesta.Size(m)
}
func (m *Respuesta) XXX_DiscardUnknown() {
	xxx_messageInfo_Respuesta.DiscardUnknown(m)
}

var xxx_messageInfo_Respuesta proto.InternalMessageInfo

func (m *Respuesta) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Respuesta) GetReloj() string {
	if m != nil {
		return m.Reloj
	}
	return ""
}

func init() {
	proto.RegisterType((*Datos)(nil), "Consulta.Datos")
	proto.RegisterType((*RespuestaBroker)(nil), "Consulta.RespuestaBroker")
	proto.RegisterType((*Consulta)(nil), "Consulta.Consulta")
	proto.RegisterType((*Respuesta)(nil), "Consulta.Respuesta")
}

func init() { proto.RegisterFile("Consulta.proto", fileDescriptor_d68347db208ce97b) }

var fileDescriptor_d68347db208ce97b = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x73, 0xce, 0xcf, 0x2b,
	0x2e, 0xcd, 0x29, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xf4,
	0xb9, 0x58, 0x5d, 0x12, 0x4b, 0xf2, 0x8b, 0x85, 0x04, 0xb8, 0x98, 0x43, 0x8b, 0x72, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xa0, 0xd4, 0x9c, 0xfc, 0x2c,
	0x09, 0x26, 0xb0, 0x18, 0x84, 0xa3, 0x64, 0xce, 0xc5, 0x1f, 0x94, 0x5a, 0x5c, 0x50, 0x9a, 0x5a,
	0x5c, 0x92, 0xe8, 0x54, 0x94, 0x9f, 0x9d, 0x5a, 0x24, 0xc4, 0xc7, 0xc5, 0xe4, 0x19, 0x00, 0xd5,
	0xc9, 0xe4, 0x19, 0x80, 0x43, 0xa3, 0x01, 0x17, 0xdc, 0x56, 0x21, 0x15, 0x2e, 0x5e, 0xbf, 0xfc,
	0xdc, 0xa4, 0xa2, 0x54, 0x97, 0xfc, 0xdc, 0xcc, 0xbc, 0xcc, 0x7c, 0xa8, 0x66, 0x54, 0x41, 0x25,
	0x43, 0x2e, 0x4e, 0xb8, 0x55, 0xc4, 0x59, 0x62, 0x14, 0xc9, 0x25, 0x06, 0xb3, 0x24, 0x28, 0xb5,
	0x10, 0xa4, 0x33, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x9e, 0x8b, 0x1f, 0x4d, 0x46,
	0x88, 0x5f, 0x0f, 0x1e, 0x2c, 0xe0, 0x30, 0x90, 0x92, 0x44, 0x08, 0xa0, 0xf9, 0x51, 0x89, 0xc1,
	0x28, 0x84, 0x4b, 0x14, 0x26, 0x0b, 0x11, 0x83, 0x99, 0x6c, 0x8d, 0x08, 0x5e, 0x68, 0x80, 0x08,
	0x21, 0xcc, 0x81, 0x31, 0xa4, 0x84, 0xb1, 0x98, 0xad, 0xc4, 0x90, 0xc4, 0x06, 0x8e, 0x10, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x68, 0xca, 0x93, 0xa2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConsultaRequestServiceClient is the client API for ConsultaRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsultaRequestServiceClient interface {
	ConsultaRequest(ctx context.Context, in *Datos, opts ...grpc.CallOption) (*RespuestaBroker, error)
}

type consultaRequestServiceClient struct {
	cc *grpc.ClientConn
}

func NewConsultaRequestServiceClient(cc *grpc.ClientConn) ConsultaRequestServiceClient {
	return &consultaRequestServiceClient{cc}
}

func (c *consultaRequestServiceClient) ConsultaRequest(ctx context.Context, in *Datos, opts ...grpc.CallOption) (*RespuestaBroker, error) {
	out := new(RespuestaBroker)
	err := c.cc.Invoke(ctx, "/Consulta.ConsultaRequestService/ConsultaRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsultaRequestServiceServer is the server API for ConsultaRequestService service.
type ConsultaRequestServiceServer interface {
	ConsultaRequest(context.Context, *Datos) (*RespuestaBroker, error)
}

// UnimplementedConsultaRequestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConsultaRequestServiceServer struct {
}

func (*UnimplementedConsultaRequestServiceServer) ConsultaRequest(ctx context.Context, req *Datos) (*RespuestaBroker, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsultaRequest not implemented")
}

func RegisterConsultaRequestServiceServer(s *grpc.Server, srv ConsultaRequestServiceServer) {
	s.RegisterService(&_ConsultaRequestService_serviceDesc, srv)
}

func _ConsultaRequestService_ConsultaRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Datos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultaRequestServiceServer).ConsultaRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Consulta.ConsultaRequestService/ConsultaRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultaRequestServiceServer).ConsultaRequest(ctx, req.(*Datos))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsultaRequestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Consulta.ConsultaRequestService",
	HandlerType: (*ConsultaRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultaRequest",
			Handler:    _ConsultaRequestService_ConsultaRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Consulta.proto",
}

// ConsultaBrokerServiceClient is the client API for ConsultaBrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsultaBrokerServiceClient interface {
	ConsultaBroker(ctx context.Context, in *Consulta, opts ...grpc.CallOption) (*Respuesta, error)
}

type consultaBrokerServiceClient struct {
	cc *grpc.ClientConn
}

func NewConsultaBrokerServiceClient(cc *grpc.ClientConn) ConsultaBrokerServiceClient {
	return &consultaBrokerServiceClient{cc}
}

func (c *consultaBrokerServiceClient) ConsultaBroker(ctx context.Context, in *Consulta, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/Consulta.ConsultaBrokerService/ConsultaBroker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsultaBrokerServiceServer is the server API for ConsultaBrokerService service.
type ConsultaBrokerServiceServer interface {
	ConsultaBroker(context.Context, *Consulta) (*Respuesta, error)
}

// UnimplementedConsultaBrokerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConsultaBrokerServiceServer struct {
}

func (*UnimplementedConsultaBrokerServiceServer) ConsultaBroker(ctx context.Context, req *Consulta) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsultaBroker not implemented")
}

func RegisterConsultaBrokerServiceServer(s *grpc.Server, srv ConsultaBrokerServiceServer) {
	s.RegisterService(&_ConsultaBrokerService_serviceDesc, srv)
}

func _ConsultaBrokerService_ConsultaBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consulta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultaBrokerServiceServer).ConsultaBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Consulta.ConsultaBrokerService/ConsultaBroker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultaBrokerServiceServer).ConsultaBroker(ctx, req.(*Consulta))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsultaBrokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Consulta.ConsultaBrokerService",
	HandlerType: (*ConsultaBrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultaBroker",
			Handler:    _ConsultaBrokerService_ConsultaBroker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Consulta.proto",
}
