// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: CompartirZF.proto

package CompartirZF

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Compartir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IP      string `protobuf:"bytes,3,opt,name=IP,proto3" json:"IP,omitempty"`
	Reloj   string `protobuf:"bytes,4,opt,name=reloj,proto3" json:"reloj,omitempty"`
}

func (x *Compartir) Reset() {
	*x = Compartir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CompartirZF_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Compartir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compartir) ProtoMessage() {}

func (x *Compartir) ProtoReflect() protoreflect.Message {
	mi := &file_CompartirZF_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compartir.ProtoReflect.Descriptor instead.
func (*Compartir) Descriptor() ([]byte, []int) {
	return file_CompartirZF_proto_rawDescGZIP(), []int{0}
}

func (x *Compartir) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Compartir) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Compartir) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *Compartir) GetReloj() string {
	if x != nil {
		return x.Reloj
	}
	return ""
}

type Respuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reloj string `protobuf:"bytes,1,opt,name=reloj,proto3" json:"reloj,omitempty"`
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CompartirZF_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_CompartirZF_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_CompartirZF_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta) GetReloj() string {
	if x != nil {
		return x.Reloj
	}
	return ""
}

var File_CompartirZF_proto protoreflect.FileDescriptor

var file_CompartirZF_proto_rawDesc = []byte{
	0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x72, 0x5a, 0x46, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x72, 0x5a, 0x46,
	0x22, 0x5f, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x6c, 0x6f, 0x6a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x6f,
	0x6a, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x65, 0x6c, 0x6f, 0x6a, 0x32, 0x55, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x72, 0x5a, 0x46, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x72, 0x5a, 0x46, 0x12, 0x16, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x72, 0x5a, 0x46, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x72, 0x1a, 0x16, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x72, 0x5a, 0x46, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_CompartirZF_proto_rawDescOnce sync.Once
	file_CompartirZF_proto_rawDescData = file_CompartirZF_proto_rawDesc
)

func file_CompartirZF_proto_rawDescGZIP() []byte {
	file_CompartirZF_proto_rawDescOnce.Do(func() {
		file_CompartirZF_proto_rawDescData = protoimpl.X.CompressGZIP(file_CompartirZF_proto_rawDescData)
	})
	return file_CompartirZF_proto_rawDescData
}

var file_CompartirZF_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CompartirZF_proto_goTypes = []interface{}{
	(*Compartir)(nil), // 0: CompartirZF.Compartir
	(*Respuesta)(nil), // 1: CompartirZF.Respuesta
}
var file_CompartirZF_proto_depIdxs = []int32{
	0, // 0: CompartirZF.CompartirZFService.CompartirZF:input_type -> CompartirZF.Compartir
	1, // 1: CompartirZF.CompartirZFService.CompartirZF:output_type -> CompartirZF.Respuesta
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CompartirZF_proto_init() }
func file_CompartirZF_proto_init() {
	if File_CompartirZF_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CompartirZF_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Compartir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CompartirZF_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CompartirZF_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CompartirZF_proto_goTypes,
		DependencyIndexes: file_CompartirZF_proto_depIdxs,
		MessageInfos:      file_CompartirZF_proto_msgTypes,
	}.Build()
	File_CompartirZF_proto = out.File
	file_CompartirZF_proto_rawDesc = nil
	file_CompartirZF_proto_goTypes = nil
	file_CompartirZF_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CompartirZFServiceClient is the client API for CompartirZFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CompartirZFServiceClient interface {
	CompartirZF(ctx context.Context, in *Compartir, opts ...grpc.CallOption) (*Respuesta, error)
}

type compartirZFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompartirZFServiceClient(cc grpc.ClientConnInterface) CompartirZFServiceClient {
	return &compartirZFServiceClient{cc}
}

func (c *compartirZFServiceClient) CompartirZF(ctx context.Context, in *Compartir, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/CompartirZF.CompartirZFService/CompartirZF", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompartirZFServiceServer is the server API for CompartirZFService service.
type CompartirZFServiceServer interface {
	CompartirZF(context.Context, *Compartir) (*Respuesta, error)
}

// UnimplementedCompartirZFServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCompartirZFServiceServer struct {
}

func (*UnimplementedCompartirZFServiceServer) CompartirZF(context.Context, *Compartir) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompartirZF not implemented")
}

func RegisterCompartirZFServiceServer(s *grpc.Server, srv CompartirZFServiceServer) {
	s.RegisterService(&_CompartirZFService_serviceDesc, srv)
}

func _CompartirZFService_CompartirZF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Compartir)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompartirZFServiceServer).CompartirZF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CompartirZF.CompartirZFService/CompartirZF",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompartirZFServiceServer).CompartirZF(ctx, req.(*Compartir))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompartirZFService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CompartirZF.CompartirZFService",
	HandlerType: (*CompartirZFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompartirZF",
			Handler:    _CompartirZFService_CompartirZF_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CompartirZF.proto",
}
